# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0046_auto_20180725_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
