# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0047_reply_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['commented_at']},
        ),
    ]
