# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0048_auto_20180726_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
