# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-26 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0049_auto_20180726_0311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='askaquestion',
            unique_together=set([]),
        ),
    ]
