# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0051_auto_20180730_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select_tag',
            name='select_tag_1',
        ),
        migrations.AlterField(
            model_name='askaquestion',
            name='select_tag',
            field=models.ManyToManyField(to='feeds.AllTags'),
        ),
        migrations.DeleteModel(
            name='Select_Tag',
        ),
    ]
