# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0058_auto_20180803_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='askaquestion',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
